repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        name: "Check: no merge conflict strings"
      - id: check-ast
        name: "Check: parse .py files"
        language_version: python3.12
      - id: check-json
        name: "Check: parse .json files"
      - id: check-toml
        name: "Check: parse .toml files"
      - id: check-yaml
        name: "Check: parse .yaml files"
      - id: check-case-conflict
        name: "Check: no case conflicting file names"
      - id: trailing-whitespace
        name: "Lint : remove trailing whitespaces"
      - id: end-of-file-fixer
        name: "Lint : files end with only newline"
      - id: mixed-line-ending
        name: "Lint : consistent file ending"
      - id: detect-private-key
        name: "Check: no private keys are commited"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-check
        name: ruff linter
      - id: ruff-format
        name: ruff formatter

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.16
    hooks:
      - id: uv-lock
      - id: uv-export
        name: main dependencies
        args:
          - "--frozen"
          - "--output-file=requirements.txt"
          - "--no-default-groups"
          - "--quiet"
          - "--no-annotate"
          - "--no-hashes"
          - "--project=backend"
          - "--no-header"
          - "--no-cache"
      - id: uv-export
        name: dev dependencies
        args:
          - "--frozen"
          - "--output-file=requirements.dev.txt"
          - "--all-groups"
          - "--quiet"
          - "--no-annotate"
          - "--no-hashes"
          - "--project=backend"
          - "--no-header"
          - "--no-cache"
